name=Whitestar Loader
description=Ghidra ROM loader for Stern Whitestar game ROMs. Builds the complete memory map including banked ROM overlays, interrupt vectors, and known OS RAM symbols for the Motorola 68B09E CPU.
author=https://github.com/c0rner/ghidra_whitestar_loader
createdOn=2026-05-01
version=@extversion@
